### ISSUE TITLE
Debian 9 jdk/jre package wrong

### ISSUE THREAD

**Issue by fugit** [example42/tinydata#34]
## Expected Behavior 
install openjdk-8-jdk or openjdk-8-jre

## Actual Behavior
attempts to install  openjdk-8-{jdk,jre}

## Steps to Reproduce the Problem

  1. attempt to install openjdk-{jdk,jre} via tp

## Specifications

Please add this info:

  1. description => "Debian GNU/Linux 9.7 (stretch)",
  1. puppet --version 5.5.10
  1. hiera reference:
psick::profiles::linux_classes:
  jenkins: psick::jenkins

**Comment by alvagante** [comment]
Old ticket. Closing. Please reopen if still actual.
