### ISSUE TITLE
hashicorp repo url for Debian has changed

### ISSUE THREAD

**Issue by florusboth** [example42/tinydata#41]
## Expected Behavior 
Activating the upstream_repo should for example make vault installable on Debian10 Buster

## Actual Behavior
The content of the repo file is:

`deb https://apt.releases.hashicorp.com stable main
`

## Steps to Reproduce the Problem

    tp::install { 'vault': and set upstream_repo to true

## Specifications

the stable should be replaced but the debian distro name, in my case buster (lsb_release -cs).

Please add this info:

  1. Output of ```facter -p``` on the failing node (at least the OS related facts)
  1. Version of Puppet and of the module
  1. The relevant Puppet code and eventually Hiera data

**Comment by alvagante** [comment]
.you have to pass auto_prereq => true to the tp::install define
