### ISSUE TITLE
python-pip on Fedora36+ is python3-pip

### ISSUE THREAD

**Issue by florusboth** [example42/tinydata#62]
# Describe your issue

tp test:

```
rpm -qi python-pip
package python-pip is not installed
```

Fedora36+ (34+?) uses python3-pip like RedHat9

## Labels

Please use the following labels:

*   **tinydata request** for any request for new or updated tinydata for an application
*   **questions** for any error you find, doubt or clarification request

## Context

Please provide any info useful for troubleshooting, like:

1.  Output of `facter -p` on the failing node (at least the OS related facts)
2.  Version of Puppet and of the module
3.  The relevant Puppet code and eventually Hiera data

**Comment by alvagante** [comment]
merged pr
